### ISSUE TITLE
Safari / Firefox compatibility

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#57] opened 2019-07-31 19:03 UTC
Needs at least a writablestream polyfill

**Comment by awendland** [comment] 2019-07-31 20:20
Error on Firefox
<img width="839" alt="Screen Shot 2019-07-31 at 1 19 43 PM 1" src="https://user-images.githubusercontent.com/1152104/62245177-e1b8e280-b395-11e9-9ebb-e034b7171c6f.png">

**Comment by eligrey** [comment] 2019-07-31 20:31
Browser support for the native WritableStream constructor:

[<img width="1037" alt="Screen Shot 2019-07-31 at 1 30 57 PM" src="https://user-images.githubusercontent.com/46995/62245935-7d971e00-b397-11e9-8141-47637aa6d036.png">](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream/WritableStream#Browser_compatibility)

**Comment by eligrey** [comment] 2019-08-12 18:44
Fixing this today.

**Comment by eligrey** [comment] 2019-08-13 19:20
Fixed in #65

**Comment by eligrey** [comment] 2019-08-13 20:37
#65 fixes this for small files. In order to support large files in Firefox we can either look into using the above polyfill and adapter or simply wait for Firefox to gain support for the WritableStream constructor.

**Comment by bencmbrook** [comment] 2019-08-13 20:53
Is the issue that (A) neither browser supports WritableStreams and (B) FireFox has a smaller Blob size limit?

**Comment by eligrey** [comment] 2019-08-13 21:05
Yes, both A & B are issues. The issue is not a show-stopper for Safari, it just makes the demo seem much less responsive.

**Closed** 2019-08-13 21:10 UTC
